version: 2.1

jobs:
  test:
    working_directory: ~/grocery-shopping-list
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    working_directory: ~/grocery-shopping-list
    steps:
      - checkout
      - run: npm install
      - run: npm run build
workflows:
  build_test:
    jobs:
      - test
      - build
