version: 2.1

orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    executor: 
      name: node/default
      tag: '16'
    steps:
      - checkout
      - run: npm install
      - run: npm run build
